site_name: drone-wrapper
site_description: Djano REST API for Tello drone SDK
repo_url: https://github.com/KKodiac/drone-wrapper-api
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/KKodiac">KKodiac</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
    - Drones: 'api/drones.md'
    - Decks: 'api/decks.md'
    - Flights: 'api/fligts.md'
    - FlightRecords: 'api/flights_records.md'

