# Generated by Django 4.0.2 on 2022-03-14 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_flightrecord_remove_drone_flight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drone',
            name='deck',
        ),
        migrations.AddField(
            model_name='drone',
            name='deck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.deck'),
        ),
    ]
