# Generated by Django 4.0.2 on 2022-03-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_remove_drone_deck_drone_deck'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='end_time',
            new_name='auto_end_time',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='start_time',
            new_name='auto_start_time',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='deck_status',
        ),
        migrations.AddField(
            model_name='deck',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drone',
            name='drone_alias',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='drone',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
