# Generated by Django 4.0.2 on 2022-03-31 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stats', '0005_remove_flight_drone_id_remove_flightrecord_flight_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='admin_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='drone',
            name='flight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.flight'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='auto_end_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='auto_start_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_path',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_record_url',
            field=models.URLField(blank=True),
        ),
    ]
