# Generated by Django 4.0.2 on 2022-05-29 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_alter_drone_deck_alter_drone_drone_alias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='auto_end_time',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='auto_start_time',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='flight_record',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='flight_record_url',
        ),
    ]
