# Generated by Django 4.0.2 on 2022-05-30 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0010_flight_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drone',
            name='deck',
        ),
        migrations.DeleteModel(
            name='Deck',
        ),
    ]
