# Generated by Django 4.0.2 on 2022-05-30 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0011_remove_drone_deck_delete_deck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='admin',
        ),
    ]
